Query       ::= EXPLAIN* (SELECT | SELECT 'UNION ALL' SELECT | SELECT ('EXCEPT' | 'EXCEPT DISTINCT') SELECT  | INSERT)
EXPLAIN     ::= 'SELECT'| 'INSERT'
SELECT      ::= 'SELECT' ((column (',' column)*) | cast ) 'FROM' (table (',' table)* | SELECT) ('AS' alias)? ( ('INNER')? 'JOIN' (table | SELECT | VALUES) ('AS' alias)? 'ON' expression )? ( 'WHERE' expression )? ( 'GROUP BY' expression )?
VALUES      ::= '(' (row (',' row)*) ')' 
row         ::= '(' (value (',' value)*) ')' 
column      ::= '*' | table '.' '*' | expression | expression 'AS' alias
expression  ::= expression 'OR' expression
               | expression 'AND' expression
               | expression ('* | / | + | -| = | > | >= | < | <= | <> | <= | <> | != | IS NULL | IS NOT NULL') expression
               | expression 'BETWEEN' expression 'AND' expression
               | reference
               | SELECT
               | value
reference   ::= ((table | '"' table '"') '.')? (alias | '"' alias '"')
value       ::= 'TRUE'
                | 'FALSE'
                | 'NULL'
                | '?'
                | INTEGER
                | UNSIGNED
                | DOUBLE
                | DECIMAL
                | STRING
                | row
cast        ::= 'CAST' '(' expression 'AS' type ')'
type        ::= 'ANY'
                | 'BOOL'
                | 'BOOLEAN'
                | 'DECIMAL'
                | 'DOUBLE'
                | 'INT'
                | 'INTEGER'
                | 'NUMBER'
                | 'SCALAR'
                | 'STRING'
                | 'TEXT'
                | 'UNSIGNED'
                | 'VARCHAR' ('(' length ')')?
INSERT      ::= 'INSERT' 'INTO' (table (',' table)*) ('(' reference (',' reference)* ')')?  VALUES '(' row ')'



